export const PRIVACY_EN = `Privacy Policy

This privacy policy applies to the Sakan app (hereinafter referred to as "Application") for mobile devices that was created by the Service Provider as a commercial service. This service is intended for use "AS IS".

Information Collection and Use

For a better experience while using the Application, the Service Provider may require you to provide certain personally identifiable information, including but not limited to:

Identity Data: First name and last name.
Contact Data: Phone number.
User-Generated Content: Profile picture (optional), city/governorate selection, and property images uploaded for listings.
Device Data: Your device's Internet Protocol address (e.g. IP address), operating system, and time spent on the Application.

The information that the Service Provider requests will be retained and used as described in this privacy policy.

Payments and Subscriptions

The Application offers paid services and subscriptions. All financial transactions are processed securely through Paymob, Google Play Billing, or Apple In-App Purchases.

No Automatic Renewal: Subscriptions in this app do not renew automatically. Access to premium services will expire unless manually renewed by the user.
Payment Security: We do not collect or store your credit card or payment method details on our servers. All transaction data is handled securely by the respective third-party payment providers.

Location Information

The Application does not request access to your device's precise GPS location. Any location-related information (such as selecting a city or governorate) is provided manually by the user to filter property listings. We use Mapbox solely for displaying maps and property locations based on data provided manually by users.

User-Generated Content (Photos)

When you upload images of properties, these images will be visible to other users of the Application to facilitate the real estate listing service. By uploading these images, you confirm that you have the right to share them.

Third Party Access

The Application utilizes third-party services that have their own privacy policies regarding handling data. Below are the third-party service providers used by the Application:

Google Play Services
Google Analytics for Firebase
Firebase Crashlytics
Mapbox
Paymob

Account Deletion Rights

Users have the right to delete their accounts and all associated data at any time. You can request account deletion by contacting us at sakan.support.team@gmail.com or through the settings within the Application. Upon request, we will permanently delete your personal information and property listings from our active databases.

Data Retention Policy

The Service Provider will retain user-provided data for as long as you use the Application and for a reasonable time thereafter. If you would like user-provided data to be deleted, please contact us via the email provided below.

Children

The Application does not address anyone under the age of 18. The Service Provider does not knowingly collect personally identifiable information from children under 18. If the Service Provider discovers that a child under 18 has provided personal information, it will immediately delete such information from our servers.

Security

The Service Provider is concerned about safeguarding the confidentiality of your information. We provide physical, electronic, and procedural safeguards to protect the information we process and maintain.

Changes

This Privacy Policy may be updated from time to time. The Service Provider will notify you of any changes by updating this page with the new Privacy Policy. You are advised to consult this Privacy Policy regularly for any changes.

This privacy policy is effective as of 1 May 2026.

Your Consent

By using the Application, you consent to the processing of your information as set forth in this Privacy Policy now and as amended by us.

Contact Us

If you have any questions regarding privacy while using the Application, or about our practices, please contact the Service Provider via email at sakan.support.team@gmail.com.

This privacy policy page was generated by an App Privacy Policy Generator and modified for custom service requirements.`;

export const PRIVACY_AR = `سياسة الخصوصية

تنطبق سياسة الخصوصية هذه على تطبيق سكان («التطبيق») للهاتف المحمول الذي أنشأه مقدّم الخدمة كخدمة تجارية. يُقدَّم هذا التطبيق «كما هو» دون أي ضمانات.

جمع المعلومات واستخدامها

لتجربة أفضل أثناء استخدام التطبيق، قد يطلب منك مقدّم الخدمة تزويدنا بمعلومات تعريفية شخصية، بما في ذلك على سبيل المثال لا الحصر:

بيانات الهوية: الاسم الأول والاسم الأخير.
بيانات الاتصال: رقم الهاتف.
المحتوى الذي يقدّمه المستخدم: صورة الملف الشخصي (اختياري)، اختيار المدينة/المحافظة، وصور العقارات المرفوعة مع الإعلانات.
بيانات الجهاز: عنوان بروتوكول الإنترنت (مثل عنوان IP)، ونظام التشغيل، والوقت المستغرق في التطبيق.

ستُحفَظ المعلومات التي يطلبها مقدّم الخدمة وتُستخدم كما هو موضّح في سياسة الخصوصية هذه.

المدفوعات والاشتراكات

يقدّم التطبيق خدمات واشتراكات مدفوعة. تُعالَج جميع المعاملات المالية بشكل آمن عبر Paymob أو Google Play Billing أو مشتريات Apple داخل التطبيق.

عدم التجديد التلقائي: لا تُجدَّد الاشتراكات تلقائياً في هذا التطبيق. تنتهي صلاحية الوصول إلى الخدمات المميزة ما لم يُجِدّدها المستخدم يدوياً.
أمان الدفع: لا نجمع أو نخزّن بيانات بطاقتك الائتمانية أو وسيلة الدفع على خوادمنا. تُعالَج جميع بيانات المعاملات بأمان لدى مزوّدي الدفع الخارجيين المعنيين.

معلومات الموقع

لا يطلب التطبيق الوصول إلى موقع GPS الدقيق لجهازك. أي معلومات مرتبطة بالموقع (مثل اختيار مدينة أو محافظة) يقدّمها المستخدم يدوياً لتصفية إعلانات العقارات. نستخدم Mapbox فقط لعرض الخرائط ومواقع العقارات استناداً إلى البيانات التي يدخلها المستخدمون يدوياً.

المحتوى الذي يقدّمه المستخدم (الصور)

عند رفع صور للعقارات، ستكون هذه الصور مرئية لمستخدمي التطبيق الآخرين لدعم خدمة الإعلانات العقارية. برفعك هذه الصور، تؤكد أنك تملك الحق في مشاركتها.

الوصول عبر أطراف ثالثة

يستخدم التطبيق خدمات أطراف ثالثة لها سياسات خصوصية خاصة بها. فيما يلي مزوّدون من الأطراف الثالثة يستخدمهم التطبيق:

Google Play Services
Google Analytics for Firebase
Firebase Crashlytics
Mapbox
Paymob

حق حذف الحساب

يحق للمستخدمين حذف حساباتهم وجميع البيانات المرتبطة في أي وقت. يمكن طلب حذف الحساب عبر التواصل معنا على sakan.support.team@gmail.com أو من خلال الإعدادات داخل التطبيق. عند الطلب، سنحذف بشكل دائم معلوماتك الشخصية وإعلاناتك العقارية من قواعد البيانات النشطة.

سياسة الاحتفاظ بالبيانات

يحتفظ مقدّم الخدمة بالبيانات التي تقدّمها ما دمت تستخدم التطبيق ولفترة معقولة بعد ذلك. لطلب حذف البيانات التي قدّمتها، يرجى التواصل عبر البريد الإلكتروني أدناه.

الأطفال

لا يستهدف التطبيق من هم دون 18 سنة. لا يجمع مقدّم الخدمة عن قصد معلومات تعريف شخصية من أطفال دون 18 سنة. إذا علِم مقدّم الخدمة أن طفلاً دون 18 زوّد بمعلومات شخصية، سيُزال هذا المحتوى فوراً من خوادمنا.

الأمان

يهتم مقدّم الخدمة بحماية سرية معلوماتك. نطبّق ضمانات مادية وإلكترونية وإجرائية لحماية المعلومات التي نعالجها ونحتفظ بها.

التعديلات

قد تُحدَّث سياسة الخصوصية هذه من وقت لآخر. سيُخطَر المستخدمون بأي تغييرات عبر تحديث هذه الصفحة بسياسة جديدة. يُنصَح بمراجعة سياسة الخصوصية بانتظام.

هذه السياسة سارية اعتباراً من 1 مايو 2026.

موافقتك

باستخدامك للتطبيق، فإنك توافق على معالجة معلوماتك وفقاً لسياسة الخصوصية هذه وما قد نُجريه من تعديلات عليها.

اتصل بنا

لأي استفسارات حول الخصوصية أثناء استخدام التطبيق أو حول ممارساتنا، يرجى التواصل مع مقدّم الخدمة عبر البريد الإلكتروني: sakan.support.team@gmail.com

تم إنشاء نص سياسة الخصوصية هذا باستخدام أداة توليد سياسات وتعديله ليتوافق مع متطلبات الخدمة.`;
